### ISSUE TITLE
cmdtheline on Hackage is out of date

### ISSUE THREAD

**Issue by gcross** [UweSchmidt/cmdtheline#1]
Hi!  I see that you've updated cmdtheline to work with GHC 7.10, but the version on Hackage still does not work with GHC 7.10, and something really needs to be done about that.  Could you try contacting the author and, if that doesn't work, take over maintenance of the package?  If you don't want to do these things I'd be happy to do them, as long as you don't mind me being the one to upload your changes.

**Comment by UweSchmidt** [comment]
Hi Greg,
I needed to do this for a few of my own programs, but I'm not very much interested in maintaining the package. If you want to overtake the maintenance, that would be great. Feel free to take all the changes I've made, and I guess for ghc-8, there will again be something to do.
